config/routes.rb
Elovation::Application.routes.draw do
  resources :games do
    resources :results, only: [:create, :destroy, :new]
    resources :ratings, only: [:index]
  end

  resources :players do
    resources :games, only: [:show], controller: 'player_games'
  end

  get '/login' => 'auth#login', as: 'login'
  get '/auth/:vendor/callback' => 'auth#callback'
  delete '/logout' => 'auth#logout', as: 'logout'

  get '/dashboard' => 'dashboard#show', as: :dashboard
  root to: 'dashboard#show'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @players = Player.all
    @games = Game.all
  end
end

app/views/dashboard/show.html.erb
<div class="row-fluid">

	<div class='span8'>
    <%=  form_for Game.first do |f| %>
<%= f.date_select :date_value, :order => [:month, :year], class: 'date-select-my' %>
<%= f.date_select :date_value, :order => [:month, :year], class: 'date-select-mdy' %>
  <% end %>

		<h1>Tournaments</h1>
		<%= link_to "New Tournament", new_game_path, class: "btn btn-primary" %>

		<ul id='games-list'>
		<% Game.all.sort_by(&:name).each do |game| %>
		  <li class="<%= "active" if @game == game %> game-list-item">
		    <%= link_to game_path(game) do %>
		    	<h3 class='game-title'><%= game.name %></h3>
		    	<ul class='game-params'>
            <li class='num-players'><%= game.players.length %> players</li>
            <li class='games-played'><%= game.results.length %> games played</li>
		    	</ul>

          <% result = game.recent_results.limit(1).first %>
          <% if result %>
            <div class='recent-result'>
              <h4>Last game</h4>
              <div class='description'>

                <% result.teams.each_with_index do |team, i| %>
                  <% team.players.each do |winner| %>
                    <span class='player'>
                      <strong><%= winner.name %></strong>
                    </span>
                  <% end %>
                  <% if i == 0 %>
                    <span> <%= Lexicon.defeated %> </span>
                  <% end %>
                <% end %>
                <br/>
                <time><%= format_time(result.created_at) %></time>
              </div>
            </div>
          <% end %>


		    <% end %>
		  </li>
		<% end %>
		</ul>
	</div>

	<div class='span4'>
		<div class='well'>
			<h2>Players</h2>

			<ul id='players-list'>
        <% @players.sort_by(&:highest_elo).reverse.each_with_index do |player, i|%>
					<li class="<%= "active" if current_player == player %> <%= "first" if i == 0 %> <%= "second" if i == 1 %> <%= "third" if i == 2 %>">
					<%= link_to player_path(player) do %>
						<%= image_tag(player.profile_picture) %>
            <span>
						  <%= player.name %>
            </span>
            <span>
              Highest Ranking: <%= player.highest_elo %>
            </span>
					<% end %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>

</div>