config/routes.rb
Elovation::Application.routes.draw do
  resources :games do
    resources :results, only: [:create, :destroy, :new]
    resources :ratings, only: [:index]
  end

  resources :players do
    resources :games, only: [:show], controller: 'player_games'
  end

  get '/login' => 'auth#login', as: 'login'
  get '/auth/:vendor/callback' => 'auth#callback'
  delete '/logout' => 'auth#logout', as: 'logout'

  get '/dashboard' => 'dashboard#show', as: :dashboard
  root to: 'dashboard#show'
end

app/views/shared/_result.html.erb
<li class="<%= 'new' if result.most_recent? -%>">
  <% result.teams.each_with_index do |team, i| %>
    <% team.players.each do |winner| %>
      <% if current_player.guid == winner.guid %>
        <%= link_to winner, class: 'player current_player' do %>
          <%= image_tag(winner.profile_picture) %>
          <% if i == 1 %>
            <strong class='loser'> <%= winner.name %></strong>
          <% else %>
            <strong> <%= winner.name %></strong>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to winner, class: 'player' do %>
          <%= image_tag(winner.profile_picture) %>
          <% if i == 1 %>
            <strong class='loser'> <%= winner.name %></strong>
          <% else %>
            <strong> <%= winner.name %></strong>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

    <% if i == 0 %>
      <% if result.tie? %>
        <small>ties</small>
      <% else %>
        <small> <%= Lexicon.defeated %> </small>
      <% end %>
    <% end %>
  <% end %>

  <% if show_game %>
    in
    <strong><%= link_to result.game.name, result.game %></strong>
  <% end %>
  <time><%= format_time(result.created_at) %></time>

  <% if result.most_recent? -%>
    <%= link_to "Delete", game_result_path(result.game, result), class: "btn btn-danger", method: :delete, confirm: "Are you sure?" %>
  <% end -%>
</li>

app/views/shared/_results.html.erb
<ol id='results'>
  <%= render partial: 'shared/result', collection: results, locals: {show_game: show_game} %>
</ol>