config/routes.rb
Elovation::Application.routes.draw do
  resources :games do
    resources :results, only: [:create, :destroy, :new]
    resources :ratings, only: [:index]
  end

  resources :players do
    resources :games, only: [:show], controller: 'player_games'
  end

  get '/login' => 'auth#login', as: 'login'
  get '/auth/:vendor/callback' => 'auth#callback'
  delete '/logout' => 'auth#logout', as: 'logout'

  get '/dashboard' => 'dashboard#show', as: :dashboard
  root to: 'dashboard#show'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :ratings, dependent: :destroy
  has_many :results, dependent: :destroy

  RATER_MAPPINGS = {
    "elo" => Rater::EloRater.new,
    "trueskill" => Rater::TrueSkillRater.new
  }

  validates :name, presence: true
  validates :rating_type, inclusion: { in: RATER_MAPPINGS.keys, message: "must be a valid rating type" }
  validate do |game|
    if game.rater
      game.rater.validate_game game
    end
  end

  validates :min_number_of_teams, numericality: { only_integer: true, greater_than_or_equal_to: 2 }
  validates :max_number_of_teams, numericality: { only_integer: true, allow_nil: true }
  validate do |game|
    if game.min_number_of_teams && game.max_number_of_teams && game.min_number_of_teams > game.max_number_of_teams
      game.errors.add(:max_number_of_teams, "cannot be less than the minimum")
    end
  end

  validates :min_number_of_players_per_team, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :max_number_of_players_per_team, numericality: { only_integer: true, allow_nil: true }
  validate do |game|
    if game.min_number_of_players_per_team && game.max_number_of_players_per_team && game.min_number_of_players_per_team > game.max_number_of_players_per_team
      game.errors.add(:max_number_of_teams, "cannot be less than the minimum")
    end
  end

  validate do |game|
    if game.rating_type_was && game.rating_type_changed?
      game.errors.add(:rating_type, "cannot be changed")
    end
  end

  validates :allow_ties, inclusion: { in: [true, false], message: "must be selected" }

  def all_ratings
    ratings.order(value: :desc)
  end

  def as_json(options = {})
    {
      name: name,
      ratings: top_ratings.map(&:as_json),
      results: recent_results.map(&:as_json)
    }
  end

  def players
    ratings.map(&:player)
  end

  def recent_results
    results.order("created_at DESC").limit(20)
  end

  def top_ratings
    ratings.order("value DESC").limit(5)
  end

  def rater
    RATER_MAPPINGS[rating_type]
  end

  def recalculate_ratings!
    RatingHistoryEvent.joins(:rating).where(ratings: {game_id: self.id}).destroy_all
    Rating.where(game_id: self.id).destroy_all

    results.order("id ASC").all.each do |result|
      rater.update_ratings self, result.teams.order("rank ASC")
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:destroy, :edit, :show, :update]

  def create
    @game = Game.new(games_params)

    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def destroy
    @game.destroy if @game.results.empty?
    redirect_to dashboard_path
  end

  def edit
  end

  def new
    @game = Game.new min_number_of_players_per_team: 1,
                     rating_type: "trueskill",
                     min_number_of_teams: 2,
                     allow_ties: true
  end

  def show
    respond_to do |format|
      format.html
      format.json do
        render json: @game
      end
    end
  end

  def update
    if @game.update_attributes(games_params)
      redirect_to game_path(@game)
    else
      render :edit
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def games_params
    params.require(:game).permit(:name,
                                :rating_type,
                                :min_number_of_teams,
                                :max_number_of_teams,
                                :min_number_of_players_per_team,
                                :max_number_of_players_per_team,
                                :allow_ties)
  end
end

app/views/games/_elo_form.html.erb
<%= form_for @game, html: {class: "form-horizontal"} do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :min_number_of_players_per_team, value: 1, class: "input-mini" %>
  <%= f.hidden_field :min_number_of_teams, value: 2, class: "input-mini" %>

  <h1>New Tournament</h1>

  <div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name, class: "input-xlarge" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.hidden_field :rating_type, :value => 'elo' %>
    <%= f.hidden_field :max_number_of_players_per_team, :value => 1 %>
    <%= f.hidden_field :max_number_of_teams, :value => 2 %>
    <%= f.hidden_field :allow_ties, :value => true %>

    <%= f.submit class: "btn btn-primary", value: "Create Tournament"%>
    <%= link_to "Cancel", root_path, class: "btn btn-warning" %>
  </div>

<% end %>

app/views/games/_form.html.erb
<%= form_for @game, html: {class: "form-horizontal"} do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :min_number_of_players_per_team, value: 1, class: "input-mini" %>
  <%= f.hidden_field :min_number_of_teams, value: 2, class: "input-mini" %>

  <h1>New Tournament</h1>

  <div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name, class: "input-xlarge" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :rating_type, class: "control-label" %>
    <div class="controls">
      <%= f.select :rating_type, Game::RATER_MAPPINGS.map{|k, v| [v.description, k]}, {}, class: "input-xlarge" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :max_number_of_players_per_team, 'Maximum number of players per team', class: "control-label" %>
    <div class="controls">
      <%= f.number_field :max_number_of_players_per_team, class: "input-mini" %>
      <span class="help-inline">Leave blank for no restriction</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :max_number_of_teams, 'Maximum number of teams', class: "control-label" %>
    <div class="controls">
      <%= f.number_field :max_number_of_teams, class: "input-mini" %>
      <span class="help-inline">Leave blank for no restriction</span>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.check_box :allow_ties, class: "input-mini" %>
      <%= f.label :allow_ties, class: "control-label" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", root_path, class: "btn btn-warning" %>
  </div>

<% end %>

app/views/games/_rating.html.erb
<tr>
	<td>
	  <div class='player'>
		<%= image_tag(rating.player.profile_picture) %>
		<%= link_to rating.player.name, player_game_path(rating.player, @game) %>
	  </div>
	</td>

	<td><%= rating.value %></td>
  <td><%= rating.player.results.for_game(rating.game).wins.size %></td>
  <td><%= rating.player.results.for_game(rating.game).losses.size %></td>
</tr>

app/views/games/edit.html.erb
<%= render 'elo_form' %>

app/views/games/new.html.erb
<%= render 'elo_form' %>

app/views/games/show.html.erb
<h1>Tournaments / <%= @game.name %></h1>

<% if current_player.is_admin? %>
  <section class="action-buttons">
    <%= link_to 'Edit', edit_game_path(@game), class: "btn" %>
    <% if @game.results.empty? %>
      <%= link_to "Delete", game_path(@game), method: :delete, confirm: "Are you sure?", class: "btn btn-danger" %>
    <% end %>
  </section>
<% end %>

<div class="row-fluid">
  <div class="span7">
    <h2>Recent Games</h2>
    <%= link_to "Add Result", new_game_result_path(@game), class: "btn btn-primary" %>

    <% if @game.recent_results.any? %>
      <%= render partial: 'shared/results', object: @game.recent_results, locals: {show_game: false} %>
    <% else %>
      <span>No results, play some games!</span>
    <% end %>

  </div>

  <div class="span5">
    <h2>Player Ratings</h2>
    <table id='ratings'>
      <thead>
        <tr>
          <th>Player</th>
          <th>Rating</th>
          <th>W</th>
          <th>L</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'rating', collection: @game.all_ratings.select(&:active?) %>
      </tbody>
    </table>
    <%= link_to "View All", game_ratings_path(@game) %>
  </div>
</div>